# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='personChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ones', models.PositiveSmallIntegerField()),
                ('fives', models.PositiveSmallIntegerField()),
                ('tens', models.PositiveSmallIntegerField()),
                ('twenties', models.PositiveSmallIntegerField()),
                ('fifties', models.PositiveSmallIntegerField()),
                ('hundreds', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
